config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'task/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  delete 'tasks/:id', to: 'tasks#destroy'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:id, :title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <% unless f.object.new_record? %>
    <%= f.input :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit the task</h1>
  <%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<h1>List of Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.completed ? '✌🏼' : '[ ]' %> <%= link_to task.title, task_path(task.id) %> <%= link_to '🗑', task_path(task.id), method: :delete %></li>
  <% end %>
</ul>

<br/>
<%= link_to 'New', task_new_path %>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Add a task</h1>
  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h2>
  <p>Task id --> <%= @task.id %></p>
  <p id="task_detail" >Task details --> <%= @task.details %></p>
  <p>Task completed --> <%= @task.completed %></p>

  <br/>
  <%= link_to 'Edit this task', edit_task_path %>

  <br/>
  <%= link_to 'Back', tasks_path %>

</div>